/* ============
 * 장바구니 Basket Store 의 Mutation Type
 * ============
 */

export const PUSH_GOODS_TO_BASKET = 'PUSH_GOODS_TO_BASKET';
export const TOGGLE_CHECK_ITEM_ON_BASKET = 'TOGGLE_CHECK_ITEM_ON_BASKET';
export const CHECK_ALL_ITEMS_ON_BASKET = 'CHECK_ALL_ITEMS_ON_BASKET';
export const UNCHECK_ALL_ITEMS_ON_BASKET = 'UNCHECK_ALL_ITEMS_ON_BASKET';
export const REMOVE_GOODS_FROM_BASKET = 'REMOVE_GOODS_FROM_BASKET';
export const REMOVE_CHECKED_FROM_BASKET = 'REMOVE_CHECKED_FROM_BASKET';

export default {
  PUSH_GOODS_TO_BASKET,
  TOGGLE_CHECK_ITEM_ON_BASKET,
  CHECK_ALL_ITEMS_ON_BASKET,
  UNCHECK_ALL_ITEMS_ON_BASKET,
  REMOVE_GOODS_FROM_BASKET,
  REMOVE_CHECKED_FROM_BASKET,
};
