/* ============
 * 장바구니 Basket Store 의 Mutation Type
 * ============
 */

export const CONCAT_GOODS_LIST = 'CONCAT_GOODS_LIST';
export const CLEAR_GOODS_LIST = 'CLEAR_GOODS_LIST';
export const CHANGE_NEXT_PAGE = 'CHANGE_NEXT_PAGE';
export const CHANGE_SELECTED_GOODS = 'CHANGE_SELECTED_GOODS';
export const LOAD_START_SELECTED_GOODS = 'LOAD_START_SELECTED_GOODS';
export const LOAD_ENDED_SELECTED_GOODS = 'LOAD_ENDED_SELECTED_GOODS';

export default {
  CONCAT_GOODS_LIST,
  CLEAR_GOODS_LIST,
  CHANGE_NEXT_PAGE,
  CHANGE_SELECTED_GOODS,
  LOAD_START_SELECTED_GOODS,
  LOAD_ENDED_SELECTED_GOODS,
};
